version: 2

builds:
  - id: gh-contrib-graph
    main: .
    binary: gh-contrib-graph
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: binary
    name_template: "gh-contrib-graph_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: Jangmyun
    name: gh-contrib-graph
